export const ImageView = {
        "american beech":  require ("@/assets/plant_data/images/american_beech.png"),
        "american bittersweet":  require ("@/assets/plant_data/images/american_bittersweet.png"),
        "american holly":  require ("@/assets/plant_data/images/american_holly.png"),
        "american hornbeam":  require ("@/assets/plant_data/images/american_hornbeam.png"),
        "american spikenard":  require ("@/assets/plant_data/images/american_spikenard.png"),
        "aromatic aster":  require ("@/assets/plant_data/images/aromatic_aster.png"),
        "bald cypress":  require ("@/assets/plant_data/images/bald_cypress.png"),
        "bee balm":  require ("@/assets/plant_data/images/bee_balm.png"),
        "black cohosh":  require ("@/assets/plant_data/images/black_cohosh.png"),
        "black gum":  require ("@/assets/plant_data/images/black_gum.png"),
        "blue lobelia":  require ("@/assets/plant_data/images/blue_lobelia.png"),
        "blue wild indigo":  require ("@/assets/plant_data/images/blue_wild_indigo.png"),
        "bristle leaf sedge":  require ("@/assets/plant_data/images/bristle_leaf_sedge.png"),
        "bur oak":  require ("@/assets/plant_data/images/bur_oak.png"),
        "butterfly weed":  require ("@/assets/plant_data/images/butterfly_weed.png"),
        "buttonbush":  require ("@/assets/plant_data/images/buttonbush.png"),
        "cardinal flower":  require ("@/assets/plant_data/images/cardinal_flower.png"),
        "chinkapin oak":  require ("@/assets/plant_data/images/chinkapin_oak.png"),
        "christmas fern":  require ("@/assets/plant_data/images/christmas_fern.png"),
        "cliff goldenrod":  require ("@/assets/plant_data/images/cliff_goldenrod.png"),
        "closed gentian":  require ("@/assets/plant_data/images/closed_gentian.png"),
        "copper iris":  require ("@/assets/plant_data/images/copper_iris.png"),
        "coral honeysuckle":  require ("@/assets/plant_data/images/coral_honeysuckle.png"),
        "cross vine":  require ("@/assets/plant_data/images/cross_vine.png"),
        "dittany":  require ("@/assets/plant_data/images/dittany.png"),
        "downy serviceberry":  require ("@/assets/plant_data/images/downy_serviceberry.png"),
        "dutchman's pipe":  require ("@/assets/plant_data/images/dutchman's_pipe.png"),
        "dwarf crested iris":  require ("@/assets/plant_data/images/dwarf_crested_iris.png"),
        "eastern blazing star":  require ("@/assets/plant_data/images/eastern_blazing_star.png"),
        "eastern blue star":  require ("@/assets/plant_data/images/eastern_blue_star.png"),
        "eastern redbud":  require ("@/assets/plant_data/images/eastern_redbud.png"),
        "eastern witch hazel":  require ("@/assets/plant_data/images/eastern_witch_hazel.png"),
        "fall glade onion":  require ("@/assets/plant_data/images/fall_glade_onion.png"),
        "false aloe":  require ("@/assets/plant_data/images/false_aloe.png"),
        "flowering dogwood":  require ("@/assets/plant_data/images/flowering_dogwood.png"),
        "fringed blue star":  require ("@/assets/plant_data/images/fringed_blue_star.png"),
        "fringe tree":  require ("@/assets/plant_data/images/fringe_tree.png"),
        "glade coneflower":  require ("@/assets/plant_data/images/glade_coneflower.png"),
        "golden alexanders":  require ("@/assets/plant_data/images/golden_alexanders.png"),
        "golden currant":  require ("@/assets/plant_data/images/golden_currant.png"),
        "gray's sedge":  require ("@/assets/plant_data/images/gray's_sedge.png"),
        "harebell":  require ("@/assets/plant_data/images/harebell.png"),
        "hollow stem joe pye weed":  require ("@/assets/plant_data/images/hollow_stem_joe_pye_weed.png"),
        "indian pink":  require ("@/assets/plant_data/images/indian_pink.png"),
        "indigo bush":  require ("@/assets/plant_data/images/indigo_bush.png"),
        "largeflower bellwort":  require ("@/assets/plant_data/images/largeflower_bellwort.png"),
        "lead plant":  require ("@/assets/plant_data/images/lead_plant.png"),
        "leatherwood":  require ("@/assets/plant_data/images/leatherwood.png"),
        "little bluestem":  require ("@/assets/plant_data/images/little_bluestem.png"),
        "little flower alumroot":  require ("@/assets/plant_data/images/little_flower_alumroot.png"),
        "lovegrass":  require ("@/assets/plant_data/images/lovegrass.png"),
        "meadowsweet spiraea":  require ("@/assets/plant_data/images/meadowsweet_spiraea.png"),
        "missouri primrose":  require ("@/assets/plant_data/images/missouri_primrose.png"),
        "new jersey tea":  require ("@/assets/plant_data/images/new_jersey_tea.png"),
        "ninebark":  require ("@/assets/plant_data/images/ninebark.png"),
        "nodding wild onion":  require ("@/assets/plant_data/images/nodding_wild_onion.png"),
        "oak sedge":  require ("@/assets/plant_data/images/oak_sedge.png"),
        "overcup oak":  require ("@/assets/plant_data/images/overcup_oak.png"),
        "pagoda dogwood":  require ("@/assets/plant_data/images/pagoda_dogwood.png"),
        "pale beardtongue":  require ("@/assets/plant_data/images/pale_beardtongue.png"),
        "pale purple coneflower":  require ("@/assets/plant_data/images/pale_purple_coneflower.png"),
        "palm sedge":  require ("@/assets/plant_data/images/palm_sedge.png"),
        "pennsylvania sedge":  require ("@/assets/plant_data/images/pennsylvania_sedge.png"),
        "pink muhlygrass":  require ("@/assets/plant_data/images/pink_muhlygrass.png"),
        "prairie alum root":  require ("@/assets/plant_data/images/prairie_alum_root.png"),
        "prairie blazing star":  require ("@/assets/plant_data/images/prairie_blazing_star.png"),
        "prairie dock":  require ("@/assets/plant_data/images/prairie_dock.png"),
        "prairie dropseed":  require ("@/assets/plant_data/images/prairie_dropseed.png"),
        "prairie pussytoes":  require ("@/assets/plant_data/images/prairie_pussytoes.png"),
        "purple beardtongue":  require ("@/assets/plant_data/images/purple_beardtongue.png"),
        "purple coneflower":  require ("@/assets/plant_data/images/purple_coneflower.png"),
        "purple prairie clover":  require ("@/assets/plant_data/images/purple_prairie_clover.png"),
        "pussytoes":  require ("@/assets/plant_data/images/pussytoes.png"),
        "queen of the prairie":  require ("@/assets/plant_data/images/queen_of_the_prairie.png"),
        "rattlesnake master":  require ("@/assets/plant_data/images/rattlesnake_master.png"),
        "red maple":  require ("@/assets/plant_data/images/red_maple.png"),
        "river birch":  require ("@/assets/plant_data/images/river_birch.png"),
        "robin's plantain":  require ("@/assets/plant_data/images/robin's_plantain.png"),
        "rose mallow":  require ("@/assets/plant_data/images/rose_mallow.png"),
        "rose turtlehead":  require ("@/assets/plant_data/images/rose_turtlehead.png"),
        "rose verbena":  require ("@/assets/plant_data/images/rose_verbena.png"),
        "rough blazing star":  require ("@/assets/plant_data/images/rough_blazing_star.png"),
        "roundleaf groundsel":  require ("@/assets/plant_data/images/roundleaf_groundsel.png"),
        "shagbark hickory":  require ("@/assets/plant_data/images/shagbark_hickory.png"),
        "shining blue star":  require ("@/assets/plant_data/images/shining_blue_star.png"),
        "shooting star":  require ("@/assets/plant_data/images/shooting_star.png"),
        "showy coneflower":  require ("@/assets/plant_data/images/showy_coneflower.png"),
        "showy goldenro":  require ("@/assets/plant_data/images/showy_goldenro.png"),
        "shrubby st. john's wort":  require ("@/assets/plant_data/images/shrubby_st._john's_wort.png"),
        "side oats grama":  require ("@/assets/plant_data/images/side_oats_grama.png"),
        "solomon's seal":  require ("@/assets/plant_data/images/solomon's_seal.png"),
        "spice bush":  require ("@/assets/plant_data/images/spice_bush.png"),
        "star tickseed":  require ("@/assets/plant_data/images/star_tickseed.png"),
        "sugar maple":  require ("@/assets/plant_data/images/sugar_maple.png"),
        "supplejack":  require ("@/assets/plant_data/images/supplejack.png"),
        "swamp leather flower":  require ("@/assets/plant_data/images/swamp_leather_flower.png"),
        "swamp milkweed":  require ("@/assets/plant_data/images/swamp_milkweed.png"),
        "swamp white oak":  require ("@/assets/plant_data/images/swamp_white_oak.png"),
        "thimbleweed":  require ("@/assets/plant_data/images/thimbleweed.png"),
        "tulip tree":  require ("@/assets/plant_data/images/tulip_tree.png"),
        "vernal witch hazel":  require ("@/assets/plant_data/images/vernal_witch_hazel.png"),
        "virginia creeper":  require ("@/assets/plant_data/images/virginia_creeper.png"),
        "white goat's beard":  require ("@/assets/plant_data/images/white_goat's_beard.png"),
        "whorled milkweed":  require ("@/assets/plant_data/images/whorled_milkweed.png"),
        "wild ginger":  require ("@/assets/plant_data/images/wild_ginger.png"),
        "wild hydrangea":  require ("@/assets/plant_data/images/wild_hydrangea.png"),
        "wild quinine":  require ("@/assets/plant_data/images/wild_quinine.png"),
        "wild stonecrop":  require ("@/assets/plant_data/images/wild_stonecrop.png"),
        "woodland spiderwort":  require ("@/assets/plant_data/images/woodland_spiderwort.png"),
        "yellowwood":  require ("@/assets/plant_data/images/yellowwood.png"),
        "yellow coneflower":  require ("@/assets/plant_data/images/yellow_coneflower.png"),
        "yellow trout lily":  require ("@/assets/plant_data/images/yellow_trout_lily.png"),
        "yellow wild indigo":  require ("@/assets/plant_data/images/yellow_wild_indigo.png"),
      }